table HeartRate
	lineageTag: af01fd4e-2392-4911-85e7-c0b84d5a404c

	column timestamp
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: dc02cf61-91fb-48b4-8cf7-81cc375ee7e9
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	column heart_rate_bpm
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1cbcebf5-9f4d-40a7-a667-32f1c050fc58
		summarizeBy: sum
		sourceColumn: heart_rate_bpm

		annotation SummarizationSetBy = Automatic

	partition HeartRate = m
		mode: directQuery
		source =
				let
				    Source = AzureDataExplorer.Contents("https://trd-vhvkvcxur2e1b956ep.z5.kusto.fabric.microsoft.com", "Garmin"),
				    HeartRate1 = Source{[Name="HeartRate"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(HeartRate1,{"EventProcessedUtcTime", "EventEnqueuedUtcTime", "PartitionId", "source", "device_address"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

