table Refreshes
	lineageTag: 38749f84-aafc-4cb0-9b35-7c23ecb11831

	column xmlaRequestId
		dataType: int64
		formatString: 0
		lineageTag: dc95bc1d-76f5-4bd7-83b7-ad224f69dd58
		summarizeBy: none
		sourceColumn: xmlaRequestId

		annotation SummarizationSetBy = User

	column WorkspaceID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 97b758ff-4bcf-4a6b-acad-294f26f9d0e0
		summarizeBy: none
		sourceColumn: WorkspaceID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SemanticModelID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4b28cca-fb42-4df2-9729-9e80448131c7
		summarizeBy: none
		sourceColumn: SemanticModelID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StartDateTime
		dataType: dateTime
		formatString: dd-mmm-yy hh:mm
		lineageTag: 6469f652-3c89-49b6-ab76-9dbab7e70a0f
		summarizeBy: none
		sourceColumn: StartDateTime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column EndDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: ec655f47-39e9-49f2-bed1-cb97ba0816c0
		summarizeBy: none
		sourceColumn: EndDateTime

		annotation SummarizationSetBy = Automatic

	column RefreshDurationSeconds
		dataType: int64
		formatString: 0
		lineageTag: 0c8114a3-8177-4a56-b4bc-25fd09b143c1
		summarizeBy: none
		sourceColumn: RefreshDurationSeconds

		annotation SummarizationSetBy = User

	column CPUCost
		dataType: double
		lineageTag: c2d26afb-9096-4c73-8d1f-d334ac8676a0
		summarizeBy: none
		sourceColumn: CPUCost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Status
		dataType: string
		lineageTag: 34fa58a3-c72a-479a-a5c7-eeb89f6b79f5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 7626584b-8304-4226-b7b3-51eae23cb8f8
		summarizeBy: none
		sourceColumn: StartDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 164e190d-8dc3-4170-be13-29eb42b9f2ba
		summarizeBy: none
		sourceColumn: EndDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Refreshes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jhd74\OneDrive\Documents\Presentations\User Groups\Birmingham_Jun25\data\fact_refresh_logs.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"LogID", Int64.Type}, {"WorkspaceID", Int64.Type}, {"SemanticModelID", Int64.Type}, {"RefreshStartTime", type datetime}, {"RefreshEndTime", type datetime}, {"RefreshDurationSeconds", Int64.Type}, {"CPUCost", type number}, {"Status", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "RefreshStartTime", "RefreshStartTime - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "RefreshEndTime", "RefreshEndTime - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column1",{{"RefreshStartTime - Copy", "StartDate"}, {"RefreshEndTime - Copy", "EndDate"}, {"LogID", "xmlaRequestId"}, {"RefreshStartTime", "StartDateTime"}, {"RefreshEndTime", "EndDateTime"}}),
				    #"Extracted Date" = Table.TransformColumns(#"Renamed Columns",{{"StartDate", DateTime.Date, type date}, {"EndDate", DateTime.Date, type date}})
				in
				    #"Extracted Date"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

