table 'Dynamic Formatting'
	lineageTag: 0942ab49-c190-43c6-8fb2-61fd6df9cf2c

	measure 'Sum TestValue' = SUM( 'Dynamic Formatting'[TestValue] )
		lineageTag: 4a6967bc-0a76-4497-9739-f3319ad6c3cf

		formatStringDefinition = evaluationcontext.dynamicformatting.SCALEDFORMATTING( SELECTEDMEASURE() )

	column Category
		lineageTag: 338bca32-12c3-4712-9496-d1655a6795cc
		summarizeBy: none
		isNameInferred
		sourceColumn: [Category]

		annotation SummarizationSetBy = Automatic

	column TestValue
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: e8dde0f3-7c41-46c9-8c3f-20333836c3e1
		summarizeBy: none
		isNameInferred
		sourceColumn: [TestValue]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	partition 'Dynamic Formatting' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Category", STRING,
				    "TestValue", CURRENCY,
				    {
				        { "Small - Hundreds", 234.56},
				        { "Small - Low Thousands", 1234.78},
				        { "Thousands - Mid", 12345.67},
				        { "Thousands - High", 567890.12},
				        { "Thousands - Edge Case", 999999.99},
				        { "Millions - Low", 1234567.89},
				        { "Millions - Mid", 45678901.23},
				        { "Millions - High", 987654321.45},
				        { "Millions - Edge Case", 999999999.99},
				        { "Billions - Low", 1234567890.12},
				        { "Billions - Mid", 45678901234.56},
				        { "Billions - High", 987654321098.76},
				        { "Billions - Edge Case", 999999999999.99},
				        { "Trillions - Low", 1234567890123.45},
				        { "Trillions - High", 9876543210987.65},
				        { "Zero", 0},
				        { "Negative - Thousands", -12345.67},
				        { "Negative - Millions", -1234567.89},
				        { "Very Small", 12.34}
				    }
				)

	annotation PBI_Id = 000e7ae936004cb1b90c84491748f3a5

