table Integers
	lineageTag: 3fa91893-9b22-4ba8-b2ef-808e31a5f2a7

	measure IntToHex =
			
			EvaluationContext.Colour.Int.ToHex( SELECTEDVALUE( Integers[Value] ), BLANK() )
		lineageTag: 7db24818-edf6-42aa-bc18-bec69c1b6b1b

	measure HEXToInt =
			
			EvaluationContext.Colour.Hex.ToInt( [IntToHex] )
		formatString: 0
		lineageTag: c1c68c8f-30ef-4800-9b10-9e104f79b5f5

	column Value
		formatString: 0
		lineageTag: 66bf82b3-51ec-4070-9c65-a9575a128246
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = User

	partition Integers = calculated
		mode: import
		source = GENERATESERIES( 0, 500, 20 )

	annotation PBI_Id = 49bfc347a4a7460fb81ef9f836b14093

