table 'Semantic  Models'
	lineageTag: 5ccb73d3-2b54-4668-b957-68eec5d5f871

	column SemanticModelID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1dabce3-5090-4768-9a1d-d01304c5adf1
		summarizeBy: none
		sourceColumn: SemanticModelID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WorkspaceID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f683a381-bc6b-4f9e-b1e2-40a0efca024b
		summarizeBy: none
		sourceColumn: WorkspaceID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SemanticModelName
		dataType: string
		lineageTag: 8cf875ae-0fbf-4281-950e-ee4cac302e31
		summarizeBy: none
		sourceColumn: SemanticModelName

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Semantic  Models' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jhd74\OneDrive\Documents\Presentations\User Groups\Birmingham_Jun25\data\dim_semantic_models.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SemanticModelID", Int64.Type}, {"WorkspaceID", Int64.Type}, {"SemanticModelName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

