table Workspaces
	lineageTag: 67388bfc-d318-4996-8456-5a7bd48ebefb

	column WorkspaceID
		dataType: int64
		formatString: 0
		lineageTag: 8aa5dd79-6823-4568-a4aa-2bd1da271273
		summarizeBy: none
		sourceColumn: WorkspaceID

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: caf73eb1-bb06-4efc-8152-40c16cac3e9a
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	partition Workspaces = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jhd74\OneDrive\Documents\Presentations\User Groups\Birmingham_Jun25\data\dim_workspaces.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"WorkspaceID", Int64.Type}, {"WorkspaceName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

